name: Display Tree Command Output

on:
  pull_request:
  merge_group:

jobs:
  display-tree:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display tree command output
      run: tree -a -I '.git'
