name: Run Pull Request Checks

on:
  pull_request:
  merge_group:

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Display tree command output
      run: tree -a -I '.git'
    - name: Call pull request check for merge queue
      if: ${{ github.event_name == 'merge_group' }}
      uses: ./.github/workflows/merge-queue.yml
    - name: Call pull request check for pull request
      if: ${{ github.event_name == 'pull_request' }}
      uses: ./.github/workflows/pull-request.yml